version: "3.8"
services:
  web:
    build: .
    image: kusitms-apply-web
    ports:
      - 8000:8000
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE:-settings.settings}
    volumes:
      - ./server/data:/root/server/data
      - ./server/media:/root/server/media
    networks:
      - worker-net
  broker:
    image: redis
    networks:
      - worker-net
  worker:
    image: kusitms-apply-web
    command: python manage.py run_huey
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE:-settings.settings}
    networks:
      - worker-net
networks:
  worker-net:
