# Generated by Django 3.0.2 on 2020-01-13 16:31

import apps.apply.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.apply.models.get_image_name)),
                ('email', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=20)),
                ('birth', models.DateField()),
                ('phone', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=2)),
                ('insta', models.CharField(max_length=255)),
                ('university', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('answer_1', models.TextField()),
                ('answer_2', models.TextField()),
                ('answer_3', models.TextField()),
                ('answer_4', models.TextField()),
                ('answer_5', models.TextField()),
                ('activity_1', models.CharField(blank=True, max_length=255)),
                ('activity_2', models.CharField(blank=True, max_length=255)),
                ('activity_3', models.CharField(blank=True, max_length=255)),
                ('activity_4', models.CharField(blank=True, max_length=255)),
                ('activity_5', models.CharField(blank=True, max_length=255)),
                ('date_1_1', models.BooleanField(default=False)),
                ('date_1_2', models.BooleanField(default=False)),
                ('date_1_3', models.BooleanField(default=False)),
                ('date_1_4', models.BooleanField(default=False)),
                ('date_1_5', models.BooleanField(default=False)),
                ('date_1_6', models.BooleanField(default=False)),
                ('date_1_7', models.BooleanField(default=False)),
                ('date_2_1', models.BooleanField(default=False)),
                ('date_2_2', models.BooleanField(default=False)),
                ('date_2_3', models.BooleanField(default=False)),
                ('date_2_4', models.BooleanField(default=False)),
                ('date_2_5', models.BooleanField(default=False)),
                ('date_2_6', models.BooleanField(default=False)),
                ('date_2_7', models.BooleanField(default=False)),
                ('date_3_1', models.BooleanField(default=False)),
                ('date_3_2', models.BooleanField(default=False)),
                ('date_3_3', models.BooleanField(default=False)),
                ('date_3_4', models.BooleanField(default=False)),
                ('date_3_5', models.BooleanField(default=False)),
                ('date_3_6', models.BooleanField(default=False)),
                ('date_3_7', models.BooleanField(default=False)),
                ('date_4_1', models.BooleanField(default=False)),
                ('date_4_2', models.BooleanField(default=False)),
                ('date_4_3', models.BooleanField(default=False)),
                ('date_4_4', models.BooleanField(default=False)),
                ('date_4_5', models.BooleanField(default=False)),
                ('date_4_6', models.BooleanField(default=False)),
                ('date_4_7', models.BooleanField(default=False)),
                ('mt_avail', models.CharField(max_length=10)),
                ('ot_avail', models.CharField(max_length=10)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
