# Generated by Django 3.0.7 on 2021-02-04 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='이름')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
            ],
        ),
        migrations.AlterModelOptions(
            name='applyconfig',
            options={'verbose_name': '지원서 개별 설정', 'verbose_name_plural': '지원서 개별 설정'},
        ),
        migrations.AlterModelOptions(
            name='applyform',
            options={'verbose_name': '지원서', 'verbose_name_plural': '지원서'},
        ),
        migrations.AlterModelOptions(
            name='siteconfig',
            options={'verbose_name': '사이트 설정(기수, 지원일 등)', 'verbose_name_plural': '사이트 설정(기수, 지원일 등)'},
        ),
        migrations.AlterField(
            model_name='applyconfig',
            name='name',
            field=models.CharField(default='21기 학회원', max_length=255, verbose_name='지원서 타입(학회원, 경총, 대홍..)'),
        ),
        migrations.AlterField(
            model_name='applyconfig',
            name='notice',
            field=models.TextField(blank=True, default='\n1. \u200b제출된 지원서는 한국대학생IT경영학회 리쿠르팅 이외의 목적으로 사용되지 않음을 밝힙니다.<br><br>\n2. <b style="color: blue;">반드시 크롬 브라우저로</b> 작성해주세요!<br><br>\n3. 모바일 최적화가 되어 있지 않아, PC버전에서 작성해주시기 바랍니다.<br><br>\n4. 오류로 인해 지원서가 정상적으로 제출되지 않을 경우를 대비하여, 반드시 다른 곳에 지원서 내용을 백업하신 뒤 제출 버튼을 눌러주시길 바랍니다.<br><br>\n', verbose_name='유의사항'),
        ),
        migrations.AlterField(
            model_name='applyconfig',
            name='question_1',
            field=models.TextField(default='1번 질문', verbose_name='질문 1'),
        ),
        migrations.AlterField(
            model_name='applyconfig',
            name='question_2',
            field=models.TextField(default='2번 질문', verbose_name='질문 2'),
        ),
        migrations.AlterField(
            model_name='applyconfig',
            name='question_3',
            field=models.TextField(default='3번 질문', verbose_name='질문 3'),
        ),
        migrations.AlterField(
            model_name='applyconfig',
            name='question_4',
            field=models.TextField(default='4번 질문', verbose_name='질문 4'),
        ),
        migrations.AlterField(
            model_name='applyconfig',
            name='question_5',
            field=models.TextField(default='지금까지 했던 활동 / 하고있는 활동을 적어주세요. (ex: 학과 활동, 동아리, 봉사, 수상내역, 인턴, 기타)', verbose_name='질문 5(활동 내역)'),
        ),
        migrations.AlterField(
            model_name='applyconfig',
            name='question_6',
            field=models.TextField(default='마지막으로 하고싶은 말을 적어주세요. (분량 자유)', verbose_name='질문 6(자유롭게 하고싶은 말)'),
        ),
    ]
