# Generated by Django 3.0.2 on 2020-01-13 17:58

import apps.apply.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyform',
            name='image',
            field=models.ImageField(default='', upload_to=apps.apply.models.get_image_name),
        ),
    ]
