# Generated by Django 3.0.2 on 2020-01-28 16:13

import apps.apply.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0002_auto_20200113_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='SNSImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to=apps.apply.models.get_sns_image_name)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sns_images', to='apply.ApplyForm')),
            ],
        ),
    ]
