# Generated by Django 3.0.2 on 2020-07-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0004_auto_20200201_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyform',
            name='apply_type',
            field=models.CharField(choices=[('경영총괄팀', 'management'), ('대외홍보팀', 'public relation'), ('교육기획팀', 'education planning'), ('학회원', 'member')], default='학회원', max_length=255),
        ),
        migrations.AlterField(
            model_name='applyform',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
