# Generated by Django 3.0.2 on 2020-07-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0006_auto_20200702_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyform',
            name='answer_6',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='applyform',
            name='answer_1',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='applyform',
            name='answer_2',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='applyform',
            name='answer_3',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='applyform',
            name='answer_4',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='applyform',
            name='answer_5',
            field=models.TextField(default=''),
        ),
    ]
