# Generated by Django 3.0.7 on 2021-02-02 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0007_auto_20200704_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='학회원', max_length=255, verbose_name='지원서 타입(학회원, 경총, 대홍..)')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('notice', models.TextField(blank=True, default='', verbose_name='유의사항')),
                ('question_1', models.TextField(default='', verbose_name='질문 1')),
                ('question_2', models.TextField(default='', verbose_name='질문 2')),
                ('question_3', models.TextField(default='', verbose_name='질문 3')),
                ('question_4', models.TextField(default='', verbose_name='질문 4')),
                ('question_5', models.TextField(default='', verbose_name='질문 5(활동 내역)')),
                ('question_6', models.TextField(default='', verbose_name='질문 6(자유롭게 하고싶은 말)')),
                ('interview_start', models.DateTimeField(verbose_name='면접 시작일과 시간(한시간 단위로 설정됨)')),
                ('interview_end', models.DateTimeField(verbose_name='면접 종료일과 시간(한시간 단위로 설정됨)')),
            ],
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.IntegerField(default=0, verbose_name='기수')),
                ('president', models.CharField(default='', max_length=100, verbose_name='학회장 이름 (전화번호)')),
                ('vice_president', models.CharField(default='', max_length=100, verbose_name='부학회장 이름 (전화번호)')),
                ('start', models.DateTimeField(verbose_name='지원 시작일')),
                ('end', models.DateTimeField(verbose_name='지원 종료일')),
                ('ot_date', models.DateTimeField(verbose_name='OT 날짜')),
                ('mt_date', models.DateTimeField(verbose_name='MT 날짜')),
            ],
        ),
        migrations.RemoveField(
            model_name='applyform',
            name='date_1_1',
        ),
        migrations.RemoveField(
            model_name='applyform',
            name='date_1_2',
        ),
        migrations.RemoveField(
            model_name='applyform',
            name='date_1_3',
        ),
        migrations.RemoveField(
            model_name='applyform',
            name='date_1_4',
        ),
        migrations.RemoveField(
            model_name='applyform',
            name='date_1_5',
        ),
        migrations.RemoveField(
            model_name='applyform',
            name='date_1_6',
        ),
        migrations.RemoveField(
            model_name='applyform',
            name='date_1_7',
        ),
        migrations.RemoveField(
            model_name='applyform',
            name='date_2_1',
        ),
        migrations.RemoveField(
            model_name='applyform',
            name='date_2_2',
        ),
        migrations.RemoveField(
            model_name='applyform',
            name='date_2_3',
        ),
        migrations.RemoveField(
            model_name='applyform',
            name='date_2_4',
        ),
        migrations.RemoveField(
            model_name='applyform',
            name='date_2_5',
        ),
        migrations.RemoveField(
            model_name='applyform',
            name='date_2_6',
        ),
        migrations.RemoveField(
            model_name='applyform',
            name='date_2_7',
        ),
        migrations.RemoveField(
            model_name='applyform',
            name='date_3_1',
        ),
        migrations.RemoveField(
            model_name='applyform',
            name='date_3_2',
        ),
        migrations.RemoveField(
            model_name='applyform',
            name='date_3_3',
        ),
        migrations.RemoveField(
            model_name='applyform',
            name='date_3_4',
        ),
        migrations.RemoveField(
            model_name='applyform',
            name='date_3_5',
        ),
        migrations.RemoveField(
            model_name='applyform',
            name='date_3_6',
        ),
        migrations.RemoveField(
            model_name='applyform',
            name='date_3_7',
        ),
        migrations.RemoveField(
            model_name='applyform',
            name='date_4_1',
        ),
        migrations.RemoveField(
            model_name='applyform',
            name='date_4_2',
        ),
        migrations.RemoveField(
            model_name='applyform',
            name='date_4_3',
        ),
        migrations.RemoveField(
            model_name='applyform',
            name='date_4_4',
        ),
        migrations.RemoveField(
            model_name='applyform',
            name='date_4_5',
        ),
        migrations.RemoveField(
            model_name='applyform',
            name='date_4_6',
        ),
        migrations.RemoveField(
            model_name='applyform',
            name='date_4_7',
        ),
        migrations.AddField(
            model_name='applyform',
            name='interview_date',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='applyform',
            name='apply_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='apply.ApplyConfig'),
        ),
    ]
