# Generated by Django 3.0.7 on 2021-02-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0008_auto_20210202_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='mt_date',
            field=models.DateField(verbose_name='MT 날짜'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='ot_date',
            field=models.DateField(verbose_name='OT 날짜'),
        ),
    ]
