# Generated by Django 3.0.7 on 2021-02-02 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0009_auto_20210202_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyform',
            name='mt_avail',
        ),
        migrations.RemoveField(
            model_name='applyform',
            name='ot_avail',
        ),
    ]
